name: PR build workflow 

on:
    pull_request:
        branches:
            - master
            - testing_package_lock_gha
            
jobs:
    build:
        name: build
        runs-on: ${{ matrix.os }}
        
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest]
                version: [net452,netcoreapp2.0]
                
        steps:
        - uses: actions/checkout@v2
        
#        - uses: actions/setup-dotnet@v1
#          with:
#            dotnet-version: '5.0.x' # SDK Version to use; x will use the latest version of the 5.0 channel
            
        - name: display dotnet version
          run: dotnet --version
          
        - name: install dependencies
          run: dotnet restore sdk/AWSXRayRecorder.sln --locked-mode
          
        - name: build SDK
          run: dotnet build sdk/AWSXRayRecorder.sln --no-restore
          
        - name: run tests
          run: dotnet test sdk/test/UnitTests/bin/**/${{matrix.version}}/AWSXRayRecorder.UnitTests.dll
