name: run_tests_on_pull_request

on:
  pull_request:
    branches: [ testing_gh_actions ]

jobs:
  build_and_test:
    runs-on: windows-latest

    strategy:
      matrix:
        version: [net452,net46,net461,netcoreapp2.1,netcoreapp3.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x

      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Restore solution
        run: dotnet restore sdk/AWSXRayRecorder.sln

      - name: Build solution
        run: dotnet build sdk/AWSXRayRecorder.sln /p:SignAssembly=false

      - name: Run tests ${{ matrix.version }}
        run: dotnet test sdk/test/UnitTests
