name: run_tests_on_push
on: [push]
jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel 
      - name: Display .Net version
        run: dotnet --version
      - name: Restore solution
        run: dotnet restore sdk/AWSXRayRecorder.sln
      - name: Build solution
        run: dotnet build sdk/AWSXRayRecorder.sln /p:SignAssembly=false
      - name: Run tests
        run: dotnet test sdk/test/UnitTests
